version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/wal-server
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/execute_deploy.sh
      timeout: 60
      runas: ubuntu
#    - location: scripts/terminate.sh
#      timeout: 60
#      runas: ubuntu
#  ApplicationStart:
##    - location: scripts/deploy.sh
##      timeout: 60
##      runas: ubuntu
#    - location: scripts/deploy_new_was.sh
#      timeout: 60
#      runas: ubuntu
#    - location: scripts/health_check.sh
#      timeout: 60
#      runas: ubuntu
#    - location: scripts/switch.sh
#      timeout: 60
#      runas: ubuntu