jwt:
  token:
    secret: dXNlciBjdXN0b21pemVkIGxlbnMgcmVjb21tZW5kYXRpb24gc2VydmljZSBvbW9vbGVuIHNlcnZlciBmaWdodGluZwo=
    expired-time:
      access: 14 * 24 * 60 * 60 * 1000
      refresh: 30 * 24 * 60 * 60 * 1000