spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${WAL_LOCAL_DATABASE_URL}
    username: ${WAL_LOCAL_DATABASE_USERNAME}

  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
        default_batch_fetch_size: 1000

  rabbitmq:
    host: ${RABBIT_MQ_LOCAL_HOST}
    port: ${RABBIT_MQ_LOCAL_PORT}
    username: ${RABBIT_MQ_LOCAL_USERNAME}
    password: ${RABBIT_MQ_LOCAL_PASSWORD}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    backend.wal.auth.config: debug